### ISSUE TITLE
Crash while scanning...

### ISSUE THREAD

**Issue by dspells** [boskokg/flutter_blue#19]
I'll try to narrow this down some more but the app is crashing without stopping in the debugger even when trying to catch all exceptions.

I updated to flutter 2.8 recently (I'm not sure if that matters)
Android Studio recently updated to 2020.3.1 Patch 4
Android minSdkVersion is 27
targetSdkVersion is 31

D/AndroidRuntime(17594): Shutting down VM
E/AndroidRuntime(17594): FATAL EXCEPTION: main
E/AndroidRuntime(17594): Process: com.apcon.intellaviewmobile, PID: 17594
E/AndroidRuntime(17594): java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@924379cb: AdapterService getRemoteName
E/AndroidRuntime(17594): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
E/AndroidRuntime(17594): 	at android.os.Parcel.createException(Parcel.java:2409)
E/AndroidRuntime(17594): 	at android.os.Parcel.readException(Parcel.java:2392)
E/AndroidRuntime(17594): 	at android.os.Parcel.readException(Parcel.java:2334)
E/AndroidRuntime(17594): 	at android.bluetooth.IBluetooth$Stub$Proxy.getRemoteName(IBluetooth.java:3395)
E/AndroidRuntime(17594): 	at android.bluetooth.BluetoothDevice.getName(BluetoothDevice.java:1273)
E/AndroidRuntime(17594): 	at com.pauldemarco.flutter_blue.ProtoMaker.from(ProtoMaker.java:99)
E/AndroidRuntime(17594): 	at com.pauldemarco.flutter_blue.ProtoMaker.from(ProtoMaker.java:49)
E/AndroidRuntime(17594): 	at com.pauldemarco.flutter_blue.FlutterBluePlugin$2.onScanResult(FlutterBluePlugin.java:813)
E/AndroidRuntime(17594): 	at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:531)
E/AndroidRuntime(17594): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(17594): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(17594): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(17594): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(17594): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime(17594): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17594): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(17594): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process (17594): Sending signal. PID: 17594 SIG: 9

% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (4 available)

• No issues found!

**Comment by trueb2** [comment]
What permissions did you request in the manifest?

Necessary permissions changed between 11 and 12:
https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

**Comment by dspells** [comment]
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>

**Comment by dspells** [comment]
I've been running on 12 just fine for quite a while. Why would this happen just now?

**Comment by dspells** [comment]
I changed it to this and it still crashes

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>

**Comment by dspells** [comment]
I noticed that flutter_blue upgraded the last time that I upgraded dependencies. Has their been changes in flutter_blue recently?

**Comment by dspells** [comment]
From the documentation. It sounds like the source code should be calling ActivityCompat.requestPermissions ... with android.permission.BLUETOOTH_CONNECT. I've added that permission request into the manifest.

The BLUETOOTH_ADVERTISE, BLUETOOTH_CONNECT, and BLUETOOTH_SCAN permissions are runtime permissions. Therefore, you must explicitly request user approval in your app before you can look for Bluetooth devices, make a device discoverable to other devices, or communicate with already-paired Bluetooth devices.

**Comment by dangabdolfo** [comment]
I every one. 
Another workaround is yo call get devices function juste after your initialization. This call permit to check the BLUETOOTH_CONNECT permission and fix this issue..

Have nice day.
Daniel
